version: '3.3'
services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    networks:
      - common-network
    environment:
      MYSQL_DATABASE: ${mysql_database}
      MYSQL_ROOT_PASSWORD: ${mysql_password}
    ports:
      - '${mysql_port}:3306'
    expose:
      - '${mysql_port}'
    volumes:
      - ./mysql-data:/var/lib/mysql
  first:
    build:
      context: .
    depends_on:
      - mysql
    restart: always
    environment:
      SPRING_DATASOURCE_URL: ${mysql_url}
      SPRING_DATASOURCE_USERNAME: ${mysql_user}
      SPRING_DATASOURCE_PASSWORD: ${mysql_password}
    networks:
      - common-network
    ports:
      - '${first_port}:8080'
    expose:
      - '${first_port}'
networks:
  common-network:
    driver: bridge